<a href="https://colab.research.google.com/github/Rukawuba/Real-Estate/blob/main/Real_Estate.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
 import pandas as pd

# this CSV file contains semicolons instead of comas as separator
ds = pd.read_csv('/content/Metro_invt_fs_uc_sfrcondo_sm_month.csv', sep=',')
ds

,RegionID,SizeRank,RegionName,RegionType,StateName,2018-03-31,2018-04-30,2018-05-31,2018-06-30,2018-07-31,...,2023-04-30,2023-05-31,2023-06-30,2023-07-31,2023-08-31,2023-09-30,2023-10-31,2023-11-30,2023-12-31,2024-01-31
0,102001,0,United States,country,NaN,1421529.0,1500194.0,1592415.0,1660615.0,1709144.0,...,845834.0,880510.0,907228.0,930911.0,950311.0,959735.0,977241.0,970238.0,932237.0,889590.0
1,394913,1,"New York, NY",msa,NY,73707.0,80345.0,85864.0,90067.0,91881.0,...,44197.0,45829.0,46198.0,45506.0,43956.0,42515.0,42586.0,42068.0,39540.0,36432.0
2,753899,2,"Los Angeles, CA",msa,CA,21998.0,23784.0,25605.0,27109.0,28811.0,...,15103.0,15283.0,15378.0,15689.0,15969.0,16032.0,16167.0,15877.0,14897.0,14039.0
3,394463,3,"Chicago, IL",msa,IL,38581.0,42253.0,45757.0,47492.0,48985.0,...,21214.0,22091.0,22706.0,23228.0,23568.0,23569.0,23707.0,22957.0,21135.0,19075.0
4,394514,4,"Dallas, TX",msa,TX,24043.0,25876.0,28225.0,30490.0,32408.0,...,17959.0,19987.0,21744.0,22748.0,23251.0,23342.0,23489.0,23305.0,22577.0,21625.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
923,753929,935,"Zapata, TX",msa,TX,55.0,55.0,56.0,66.0,65.0,...,50.0,49.0,47.0,43.0,42.0,40.0,37.0,35.0,36.0,37.0
924,394743,936,"Ketchikan, AK",msa,AK,77.0,78.0,80.0,92.0,104.0,...,66.0,69.0,66.0,61.0,57.0,55.0,51.0,47.0,41.0,34.0
925,753874,937,"Craig, CO",msa,CO,115.0,116.0,126.0,148.0,165.0,...,56.0,65.0,77.0,88.0,98.0,102.0,104.0,98.0,88.0,74.0
926,395188,938,"Vernon, TX",msa,TX,21.0,26.0,32.0,39.0,39.0,...,37.0,40.0,45.0,53.0,56.0,58.0,55.0,54.0,48.0,43.0
927,394767,939,"Lamesa, TX",msa,TX,35.0,35.0,37.0,38.0,41.0,...,34.0,32.0,33.0,36.0,40.0,43.0,44.0,44.0,43.0,42.0

In [6]:
import pandas as pd

# Show all columns (without truncation)
pd.set_option('display.max_columns', None)

# Show all rows (up to a reasonable limit)
pd.set_option('display.max_rows', 50)  # Adjust this limit as needed

# Optionally, increase column width for better readability
# pd.set_option('display.max_colwidth', None)  # Uncomment if needed

# Display your data (replace 'your_data' with your actual DataFrame)
ds

,RegionID,SizeRank,RegionName,RegionType,StateName,2018-03-31,2018-04-30,2018-05-31,2018-06-30,2018-07-31,2018-08-31,2018-09-30,2018-10-31,2018-11-30,2018-12-31,2019-01-31,2019-02-28,2019-03-31,2019-04-30,2019-05-31,2019-06-30,2019-07-31,2019-08-31,2019-09-30,2019-10-31,2019-11-30,2019-12-31,2020-01-31,2020-02-29,2020-03-31,2020-04-30,2020-05-31,2020-06-30,2020-07-31,2020-08-31,2020-09-30,2020-10-31,2020-11-30,2020-12-31,2021-01-31,2021-02-28,2021-03-31,2021-04-30,2021-05-31,2021-06-30,2021-07-31,2021-08-31,2021-09-30,2021-10-31,2021-11-30,2021-12-31,2022-01-31,2022-02-28,2022-03-31,2022-04-30,2022-05-31,2022-06-30,2022-07-31,2022-08-31,2022-09-30,2022-10-31,2022-11-30,2022-12-31,2023-01-31,2023-02-28,2023-03-31,2023-04-30,2023-05-31,2023-06-30,2023-07-31,2023-08-31,2023-09-30,2023-10-31,2023-11-30,2023-12-31,2024-01-31
0,102001,0,United States,country,NaN,1421529.0,1500194.0,1592415.0,1660615.0,1709144.0,1733390.0,1723099.0,1701372.0,1642145.0,1541994.0,1452603.0,1405515.0,1449965.0,1515570.0,1604227.0,1665082.0,1693555.0,1688690.0,1665421.0,1634586.0,1560531.0,1441428.0,1336187.0,1285461.0,1309043.0,1299807.0,1317974.0,1320181.0,1345172.0,1324973.0,1283020.0,1228208.0,1140490.0,1028143.0,949576.0,881616.0,882081.0,882293.0,934109.0,978002.0,1028524.0,1071734.0,1083989.0,1067840.0,997847.0,887059.0,777085.0,706905.0,726913.0,774472.0,860326.0,946905.0,1033311.0,1092069.0,1101482.0,1085079.0,1032570.0,955889.0,884129.0,830977.0,835429.0,845834.0,880510.0,907228.0,930911.0,950311.0,959735.0,977241.0,970238.0,932237.0,889590.0
1,394913,1,"New York, NY",msa,NY,73707.0,80345.0,85864.0,90067.0,91881.0,91252.0,90050.0,89339.0,87186.0,81944.0,76678.0,74497.0,78192.0,84211.0,91255.0,95966.0,97260.0,95383.0,93359.0,91309.0,87828.0,80727.0,74301.0,72005.0,74371.0,72270.0,70474.0,70352.0,77012.0,81547.0,82809.0,80976.0,77001.0,70532.0,65541.0,61868.0,61966.0,62738.0,65965.0,68986.0,70650.0,70786.0,69101.0,67467.0,63984.0,57820.0,50768.0,46430.0,48039.0,51340.0,55710.0,58872.0,61312.0,61386.0,60262.0,58241.0,55450.0,50400.0,45916.0,42796.0,43253.0,44197.0,45829.0,46198.0,45506.0,43956.0,42515.0,42586.0,42068.0,39540.0,36432.0
2,753899,2,"Los Angeles, CA",msa,CA,21998.0,23784.0,25605.0,27109.0,28811.0,29874.0,30428.0,30606.0,30035.0,28252.0,26635.0,25849.0,27132.0,28454.0,30124.0,30980.0,31524.0,31208.0,30618.0,29591.0,27588.0,24357.0,21649.0,20624.0,21194.0,20897.0,21255.0,22209.0,24174.0,25175.0,25453.0,25306.0,24128.0,21871.0,19808.0,18781.0,19497.0,20038.0,20588.0,20766.0,21361.0,21816.0,21609.0,20711.0,18955.0,16307.0,14161.0,13376.0,14653.0,16023.0,17635.0,19187.0,21015.0,22264.0,22400.0,21802.0,20477.0,18604.0,16767.0,15382.0,15214.0,15103.0,15283.0,15378.0,15689.0,15969.0,16032.0,16167.0,15877.0,14897.0,14039.0
3,394463,3,"Chicago, IL",msa,IL,38581.0,42253.0,45757.0,47492.0,48985.0,49782.0,49630.0,48916.0,46495.0,42304.0,38250.0,36754.0,39387.0,43789.0,48113.0,50794.0,51883.0,52135.0,51829.0,50805.0,47938.0,43093.0,38966.0,37740.0,39339.0,39363.0,39734.0,40277.0,42454.0,43099.0,42308.0,40961.0,38027.0,33837.0,31354.0,29581.0,30715.0,31386.0,34006.0,36266.0,38328.0,39729.0,39806.0,38727.0,35528.0,30559.0,25580.0,22343.0,22775.0,24246.0,26775.0,28894.0,30846.0,31876.0,31682.0,30798.0,28771.0,25674.0,22770.0,20829.0,20922.0,21214.0,22091.0,22706.0,23228.0,23568.0,23569.0,23707.0,22957.0,21135.0,19075.0
4,394514,4,"Dallas, TX",msa,TX,24043.0,25876.0,28225.0,30490.0,32408.0,33567.0,33512.0,32589.0,31265.0,29283.0,27727.0,27057.0,28543.0,30513.0,32932.0,34785.0,36078.0,36285.0,35472.0,34244.0,32494.0,30122.0,28058.0,27264.0,27993.0,28231.0,29129.0,29893.0,31000.0,30306.0,28526.0,26449.0,24033.0,21385.0,19294.0,17682.0,17931.0,18591.0,20030.0,21087.0,22496.0,23661.0,23945.0,23080.0,21361.0,19025.0,16641.0,14913.0,14911.0,15053.0,16146.0,17845.0,20485.0,22365.0,22863.0,22445.0,21500.0,19985.0,18560.0,17106.0,17053.0,17959.0,19987.0,21744.0,22748.0,23251.0,23342.0,23489.0,23305.0,22577.0,21625.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
923,753929,935,"Zapata, TX",msa,TX,55.0,55.0,56.0,66.0,65.0,62.0,51.0,50.0,50.0,48.0,48.0,47.0,47.0,47.0,49.0,49.0,50.0,48.0,47.0,47.0,47.0,47.0,46.0,45.0,42.0,37.0,31.0,28.0,24.0,23.0,21.0,23.0,22.0,23.0,22.0,22.0,22.0,23.0,23.0,22.0,22.0,22.0,25.0,27.0,31.0,32.0,35.0,38.0,43.0,43.0,42.0,41.0,41.0,44.0,44.0,47.0,46.0,47.0,48.0,49.0,49.0,50.0,49.0,47.0,43.0,42.0,40.0,37.0,35.0,36.0,37.0
924,394743,936,"Ketchikan, AK",msa,AK,77.0,78.0,80.0,92.0,104.0,115.0,109.0,105.0,96.0,92.0,85.0,81.0,80.0,81.0,86.0,86.0,84.0,85.0,92.0,96.0,94.0,87.0,83.0,79.0,79.0,81.0,86.0,94.0,100.0,100.0,93.0,87.0,81.0,76.0,69.0,66.0,63.0,68.0,78.0,91.0,103.0,107.0,103.0,89.0,79.0,68.0,64.0,59.0,61.0,63.0,63.0,61.0,59.0,60.0,64.0,63.0,62.0,58.0,56.0,56.0,61.0,66.0,69.0,66.0,61.0,57.0,55.0,51.0,47.0,41.0,34.0
925,753874,937,"Craig, CO",msa,CO,115.0,116.0,126.0,148.0,165.0,175.0,169.0,161.0,145.0,129.0,113.0,105.0,104.0,115.0,130.0,146.0,161.0,169.0,175.0,169.0,159.0,142.0,130.0,127.0,134.0,143.0,158.0,169.0,183.0,183.0,181.0,168.0,149.0,125.0,105.0,90.0,83.0,84.0,82.0,77.0,71.0,77.0,82.0,89.0,84.0,74.0,60.0,51.0,52.0,60.0,68.0,72.0,74.0,80.0,84.0,82.0,75.0,66.0,55.0,49.0,48.0,56.0,65.0,77.0,88.0,98.0,102.0,104.0,98.0,88.0,74.0
926,395188,938,"Vernon, TX",msa,TX,21.0,26.0,32.0,39.0,39.0,38.0,37.0,38.0,42.0,45.0,45.0,46.0,47.0,47.0,43.0,40.0,38.0,37.0,34.0,32.0,28.0,26.0,26.0,31.0,35.0,35.0,32.0,27.0,25.0,24.0,23.0,21.0,18.0,17.0,17.0,17.0,16.0,15.0,14.0,15.0,20.0,26.0,31.0,32.0,32.0,30.0,30.0,28.0,28.0,28.0,30.0,31.0,30.0,32.0,36.0,42.0,46.0,45.0,45.0,40.0,40.0,37.0,40.0,45.0,53.0,56.0,58.0,55.0,54.0,48.0,43.0
927,394767,939,"Lamesa, TX",msa,TX,35.0,35.0,37.0,38.0,41.0,40.0,36.0,32.0,28.0,25.0,24.0,28.0,34.0,40.0,41.0,39.0,37.0,36.0,35.0,33.0,31.0,29.0,31.0,33.0,35.0,34.0,32.0,32.0,34.0,35.0,36.0,33.0,30.0,28.0,27.0,25.0,23.0,28.0,35.0,40.0,38.0,35.0,34.0,32.0,31.0,31.0,32.0,31.0,28.0,26.0,25.0,25.0,27.0,34.0,40.0,43.0,44.0,43.0,43.0,40.0,37.0,34.0,32.0,33.0,36.0,40.0,43.0,44.0,44.0,43.0,42.0

In [15]:

pd.set_option('display.max_rows', 100) # Adjust this limit as needed
ds

,RegionID,SizeRank,RegionName,RegionType,StateName,2018-03-31,2018-04-30,2018-05-31,2018-06-30,2018-07-31,2018-08-31,2018-09-30,2018-10-31,2018-11-30,2018-12-31,2019-01-31,2019-02-28,2019-03-31,2019-04-30,2019-05-31,2019-06-30,2019-07-31,2019-08-31,2019-09-30,2019-10-31,2019-11-30,2019-12-31,2020-01-31,2020-02-29,2020-03-31,2020-04-30,2020-05-31,2020-06-30,2020-07-31,2020-08-31,2020-09-30,2020-10-31,2020-11-30,2020-12-31,2021-01-31,2021-02-28,2021-03-31,2021-04-30,2021-05-31,2021-06-30,2021-07-31,2021-08-31,2021-09-30,2021-10-31,2021-11-30,2021-12-31,2022-01-31,2022-02-28,2022-03-31,2022-04-30,2022-05-31,2022-06-30,2022-07-31,2022-08-31,2022-09-30,2022-10-31,2022-11-30,2022-12-31,2023-01-31,2023-02-28,2023-03-31,2023-04-30,2023-05-31,2023-06-30,2023-07-31,2023-08-31,2023-09-30,2023-10-31,2023-11-30,2023-12-31,2024-01-31
0,102001,0,United States,country,NaN,1421529.0,1500194.0,1592415.0,1660615.0,1709144.0,1733390.0,1723099.0,1701372.0,1642145.0,1541994.0,1452603.0,1405515.0,1449965.0,1515570.0,1604227.0,1665082.0,1693555.0,1688690.0,1665421.0,1634586.0,1560531.0,1441428.0,1336187.0,1285461.0,1309043.0,1299807.0,1317974.0,1320181.0,1345172.0,1324973.0,1283020.0,1228208.0,1140490.0,1028143.0,949576.0,881616.0,882081.0,882293.0,934109.0,978002.0,1028524.0,1071734.0,1083989.0,1067840.0,997847.0,887059.0,777085.0,706905.0,726913.0,774472.0,860326.0,946905.0,1033311.0,1092069.0,1101482.0,1085079.0,1032570.0,955889.0,884129.0,830977.0,835429.0,845834.0,880510.0,907228.0,930911.0,950311.0,959735.0,977241.0,970238.0,932237.0,889590.0
1,394913,1,"New York, NY",msa,NY,73707.0,80345.0,85864.0,90067.0,91881.0,91252.0,90050.0,89339.0,87186.0,81944.0,76678.0,74497.0,78192.0,84211.0,91255.0,95966.0,97260.0,95383.0,93359.0,91309.0,87828.0,80727.0,74301.0,72005.0,74371.0,72270.0,70474.0,70352.0,77012.0,81547.0,82809.0,80976.0,77001.0,70532.0,65541.0,61868.0,61966.0,62738.0,65965.0,68986.0,70650.0,70786.0,69101.0,67467.0,63984.0,57820.0,50768.0,46430.0,48039.0,51340.0,55710.0,58872.0,61312.0,61386.0,60262.0,58241.0,55450.0,50400.0,45916.0,42796.0,43253.0,44197.0,45829.0,46198.0,45506.0,43956.0,42515.0,42586.0,42068.0,39540.0,36432.0
2,753899,2,"Los Angeles, CA",msa,CA,21998.0,23784.0,25605.0,27109.0,28811.0,29874.0,30428.0,30606.0,30035.0,28252.0,26635.0,25849.0,27132.0,28454.0,30124.0,30980.0,31524.0,31208.0,30618.0,29591.0,27588.0,24357.0,21649.0,20624.0,21194.0,20897.0,21255.0,22209.0,24174.0,25175.0,25453.0,25306.0,24128.0,21871.0,19808.0,18781.0,19497.0,20038.0,20588.0,20766.0,21361.0,21816.0,21609.0,20711.0,18955.0,16307.0,14161.0,13376.0,14653.0,16023.0,17635.0,19187.0,21015.0,22264.0,22400.0,21802.0,20477.0,18604.0,16767.0,15382.0,15214.0,15103.0,15283.0,15378.0,15689.0,15969.0,16032.0,16167.0,15877.0,14897.0,14039.0
3,394463,3,"Chicago, IL",msa,IL,38581.0,42253.0,45757.0,47492.0,48985.0,49782.0,49630.0,48916.0,46495.0,42304.0,38250.0,36754.0,39387.0,43789.0,48113.0,50794.0,51883.0,52135.0,51829.0,50805.0,47938.0,43093.0,38966.0,37740.0,39339.0,39363.0,39734.0,40277.0,42454.0,43099.0,42308.0,40961.0,38027.0,33837.0,31354.0,29581.0,30715.0,31386.0,34006.0,36266.0,38328.0,39729.0,39806.0,38727.0,35528.0,30559.0,25580.0,22343.0,22775.0,24246.0,26775.0,28894.0,30846.0,31876.0,31682.0,30798.0,28771.0,25674.0,22770.0,20829.0,20922.0,21214.0,22091.0,22706.0,23228.0,23568.0,23569.0,23707.0,22957.0,21135.0,19075.0
4,394514,4,"Dallas, TX",msa,TX,24043.0,25876.0,28225.0,30490.0,32408.0,33567.0,33512.0,32589.0,31265.0,29283.0,27727.0,27057.0,28543.0,30513.0,32932.0,34785.0,36078.0,36285.0,35472.0,34244.0,32494.0,30122.0,28058.0,27264.0,27993.0,28231.0,29129.0,29893.0,31000.0,30306.0,28526.0,26449.0,24033.0,21385.0,19294.0,17682.0,17931.0,18591.0,20030.0,21087.0,22496.0,23661.0,23945.0,23080.0,21361.0,19025.0,16641.0,14913.0,14911.0,15053.0,16146.0,17845.0,20485.0,22365.0,22863.0,22445.0,21500.0,19985.0,18560.0,17106.0,17053.0,17959.0,19987.0,21744.0,22748.0,23251.0,23342.0,23489.0,23305.0,22577.0,21625.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
923,753929,935,"Zapata, TX",msa,TX,55.0,55.0,56.0,66.0,65.0,62.0,51.0,50.0,50.0,48.0,48.0,47.0,47.0,47.0,49.0,49.0,50.0,48.0,47.0,47.0,47.0,47.0,46.0,45.0,42.0,37.0,31.0,28.0,24.0,23.0,21.0,23.0,22.0,23.0,22.0,22.0,22.0,23.0,23.0,22.0,22.0,22.0,25.0,27.0,31.0,32.0,35.0,38.0,43.0,43.0,42.0,41.0,41.0,44.0,44.0,47.0,46.0,47.0,48.0,49.0,49.0,50.0,49.0,47.0,43.0,42.0,40.0,37.0,35.0,36.0,37.0
924,394743,936,"Ketchikan, AK",msa,AK,77.0,78.0,80.0,92.0,104.0,115.0,109.0,105.0,96.0,92.0,85.0,81.0,80.0,81.0,86.0,86.0,84.0,85.0,92.0,96.0,94.0,87.0,83.0,79.0,79.0,81.0,86.0,94.0,100.0,100.0,93.0,87.0,81.0,76.0,69.0,66.0,63.0,68.0,78.0,91.0,103.0,107.0,103.0,89.0,79.0,68.0,64.0,59.0,61.0,63.0,63.0,61.0,59.0,60.0,64.0,63.0,62.0,58.0,56.0,56.0,61.0,66.0,69.0,66.0,61.0,57.0,55.0,51.0,47.0,41.0,34.0
925,753874,937,"Craig, CO",msa,CO,115.0,116.0,126.0,148.0,165.0,175.0,169.0,161.0,145.0,129.0,113.0,105.0,104.0,115.0,130.0,146.0,161.0,169.0,175.0,169.0,159.0,142.0,130.0,127.0,134.0,143.0,158.0,169.0,183.0,183.0,181.0,168.0,149.0,125.0,105.0,90.0,83.0,84.0,82.0,77.0,71.0,77.0,82.0,89.0,84.0,74.0,60.0,51.0,52.0,60.0,68.0,72.0,74.0,80.0,84.0,82.0,75.0,66.0,55.0,49.0,48.0,56.0,65.0,77.0,88.0,98.0,102.0,104.0,98.0,88.0,74.0
926,395188,938,"Vernon, TX",msa,TX,21.0,26.0,32.0,39.0,39.0,38.0,37.0,38.0,42.0,45.0,45.0,46.0,47.0,47.0,43.0,40.0,38.0,37.0,34.0,32.0,28.0,26.0,26.0,31.0,35.0,35.0,32.0,27.0,25.0,24.0,23.0,21.0,18.0,17.0,17.0,17.0,16.0,15.0,14.0,15.0,20.0,26.0,31.0,32.0,32.0,30.0,30.0,28.0,28.0,28.0,30.0,31.0,30.0,32.0,36.0,42.0,46.0,45.0,45.0,40.0,40.0,37.0,40.0,45.0,53.0,56.0,58.0,55.0,54.0,48.0,43.0
927,394767,939,"Lamesa, TX",msa,TX,35.0,35.0,37.0,38.0,41.0,40.0,36.0,32.0,28.0,25.0,24.0,28.0,34.0,40.0,41.0,39.0,37.0,36.0,35.0,33.0,31.0,29.0,31.0,33.0,35.0,34.0,32.0,32.0,34.0,35.0,36.0,33.0,30.0,28.0,27.0,25.0,23.0,28.0,35.0,40.0,38.0,35.0,34.0,32.0,31.0,31.0,32.0,31.0,28.0,26.0,25.0,25.0,27.0,34.0,40.0,43.0,44.0,43.0,43.0,40.0,37.0,34.0,32.0,33.0,36.0,40.0,43.0,44.0,44.0,43.0,42.0

In [16]:
!kaggle datasets download -d ahmedshahriarsakib/usa-real-estate-dataset

Traceback (most recent call last):
  File "/usr/local/bin/kaggle", line 5, in <module>
    from kaggle.cli import main
  File "/usr/local/lib/python3.10/dist-packages/kaggle/__init__.py", line 23, in <module>
    api.authenticate()
  File "/usr/local/lib/python3.10/dist-packages/kaggle/api/kaggle_api_extended.py", line 403, in authenticate
    raise IOError('Could not find {}. Make sure it\'s located in'
OSError: Could not find kaggle.json. Make sure it's located in /root/.kaggle. Or use the environment method.

In [17]:
! pip install kaggle

Requirement already satisfied: kaggle in /usr/local/lib/python3.10/dist-packages (1.5.16)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.10/dist-packages (from kaggle) (1.16.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.10/dist-packages (from kaggle) (2024.2.2)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.10/dist-packages (from kaggle) (2.8.2)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from kaggle) (2.31.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from kaggle) (4.66.2)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.10/dist-packages (from kaggle) (8.0.4)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.10/dist-packages (from kaggle) (2.0.7)
Requirement already satisfied: bleach in /usr/local/lib/python3.10/dist-packages (from kaggle) (6.1.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.10/dist-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.10/dist-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->kaggle) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->kaggle) (3.6)

In [19]:
!mkdir /.kaggle
!mv kaggle.json /.kaggle
!mv /.kaggle /root/
!chmod 600 ~/kaggle/kaggle.json

mv: cannot stat 'kaggle.json': No such file or directory
mv: cannot move '/.kaggle' to '/root/.kaggle': Directory not empty
chmod: cannot access '/root/kaggle/kaggle.json': No such file or directory

In [20]:
!kaggle datasets download -d ahmedshahriarsakib/usa-real-estate-dataset

Warning: Your Kaggle API key is readable by other users on this system! To fix this, you can run 'chmod 600 /root/.kaggle/kaggle.json'
Downloading usa-real-estate-dataset.zip to /content
 50% 11.0M/22.2M [00:00<00:00, 112MB/s]
100% 22.2M/22.2M [00:00<00:00, 122MB/s]

In [21]:
!chmod 600 /root/.kaggle/kaggle.json

In [22]:
!unzip usa-real-estate-dataset.zip

Archive:  usa-real-estate-dataset.zip
  inflating: realtor-data.zip.csv

In [23]:
import pandas as pd

df = pd.read_csv('realtor-data.zip.csv')

In [31]:
pd.set_option('display.max_columns', None)
df.head(5)

,status,bed,bath,acre_lot,city,state,zip_code,house_size,prev_sold_date,price
0,for_sale,3.0,2.0,0.12,Adjuntas,Puerto Rico,601.0,920.0,NaN,105000.0
1,for_sale,4.0,2.0,0.08,Adjuntas,Puerto Rico,601.0,1527.0,NaN,80000.0
2,for_sale,2.0,1.0,0.15,Juana Diaz,Puerto Rico,795.0,748.0,NaN,67000.0
3,for_sale,4.0,2.0,0.10,Ponce,Puerto Rico,731.0,1800.0,NaN,145000.0
4,for_sale,6.0,2.0,0.05,Mayaguez,Puerto Rico,680.0,NaN,NaN,65000.0

In [33]:
df.describe()

,bed,bath,acre_lot,zip_code,house_size,price
count,1.663100e+06,1.658940e+06,1.582890e+06,2.001148e+06,1.356466e+06,2.001395e+06
mean,3.386039e+00,2.428370e+00,2.758164e+01,1.096973e+04,2.143257e+03,6.539247e+05
std,1.886923e+00,1.719025e+00,1.215055e+03,5.790174e+03,3.023623e+03,2.267084e+06
min,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,4.000000e+00,0.000000e+00
25%,2.000000e+00,2.000000e+00,1.200000e-01,7.043000e+03,1.216000e+03,1.690000e+05
50%,3.000000e+00,2.000000e+00,3.000000e-01,1.136100e+04,1.719000e+03,3.490000e+05
75%,4.000000e+00,3.000000e+00,1.140000e+00,1.513200e+04,2.477000e+03,6.490000e+05
max,1.420000e+02,1.980000e+02,1.000000e+05,9.999900e+04,1.450112e+06,8.750000e+08

In [34]:
from google.colab import files

df.to_csv('realtor.csv', index=False)  # Replace 'your_data' with your DataFrame name
files.save('realtor.csv')  # This saves the file within Colab

AttributeError: module 'google.colab.files' has no attribute 'save'